<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLmzenvx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLmzenvx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLmzenvx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLmzenvx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLmzenvx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lmzenvx',
    'container.build_id' => '7c626989',
    'container.build_time' => 1776955104,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLmzenvx');
