<?php

namespace ContainerLmzenvx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__Gb8vyGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..Gb8vyG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..Gb8vyG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B', 'get_ServiceLocator_1vYpZ1BService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B', 'get_ServiceLocator_1vYpZ1BService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B', 'get_ServiceLocator_1vYpZ1BService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B', 'get_ServiceLocator_1vYpZ1BService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B', 'get_ServiceLocator_1vYpZ1BService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B', 'get_ServiceLocator_1vYpZ1BService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
        ]);
    }
}
