<?php

namespace ContainerLmzenvx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSdkControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SdkController' shared autowired service.
     *
     * @return \App\Controller\SdkController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'SdkController.php';

        $container->services['App\\Controller\\SdkController'] = $instance = new \App\Controller\SdkController(($container->privates['App\\Repository\\LicenseRepository'] ?? $container->load('getLicenseRepositoryService')), ($container->privates['App\\Repository\\MachineActivationRepository'] ?? $container->load('getMachineActivationRepositoryService')), ($container->privates['App\\Repository\\ActivityReportRepository'] ?? $container->load('getActivityReportRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\SdkController', $container));

        return $instance;
    }
}
